name: Appium CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Android setup action
      uses: kineticengines/setup-android-actions@v0.1
    - name: Install and Run Appium Server
      uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
    - name: Start Android Emulator
      run: |
        chmod +x ./scripts/run-emulator.sh
        ./scripts/run-emulator.sh.sh
    - name: Run UI Tests
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
 
