name: Appium CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Android setup action
      uses: kineticengines/setup-android-actions@v0.1
    - name: Install and Run Appium Server
      uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew test --info
