name: Appium CI
on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: echo
      run: |
          brew install docker-machine docker
          sudo docker version
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Android Github Action
      uses: Vukan-Markovic/Github-Android-Action@1.2
    - uses: malinskiy/action-android/install-sdk@release/0.0.5
    - name: Install and Run Appium Server
      uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
    - name: Start Android Emulator
      run: |
        chmod +x ./scripts/emulator.sh
        ./scripts/emulator.sh
    - name: Run UI Tests
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
 
