name: Appium CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Android Github Action
      uses: Vukan-Markovic/Github-Android-Action@1.2
    - uses: malinskiy/action-android/install-sdk@release/0.0.5
    - name: Install and Run Appium Server
      uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
    - name: Install Android System Image
      run: |
        cd $ANDROID_HOME/tools/bin
        sdkmanager "system-images;android-23;google_apis;armeabi-v7a"
        sdkmanager --licenses
    - name: Start Android Emulator
      run: | 
        echo y | $ANDROID_HOME/tools/android update sdk --no-ui -t platform-tool
        adb version
        cd $ANDROID_HOME/tools/bin
        echo no | avdmanager create avd -n test -k "system-images;android-23;google_apis;armeabi-v7a" --force
        cd ..
        emulator -avd test -no-window -no-audio -debug-init > /dev/null 2>&1 &
        echo "Waiting emulator is ready..."
        
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
        echo "Emulator is ready!"
    - name: Run UI Tests
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
 
