name: Appium CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Android Github Action
      uses: Vukan-Markovic/Github-Android-Action@1.2
    - name: Install and Run Appium Server
      uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Android Emulator
      run: |
        chmod +x ./scripts/run-emulator.sh
        ./scripts/run-emulator.sh
    - name: Build with Gradle
      run: ./gradlew test
